server:
  port: 8080

spring:
  application:
    name: eolma-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

jwt:
  access-token-expiry: 1800000   # 30min
  refresh-token-expiry: 604800000 # 7days
